# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(choices=[('Breed_C', 'Breed C'), ('Breed_NC', 'Breed NC'), ('tmp', 'tmp value')], max_length=8, verbose_name='breed')),
                ('policy_id', models.CharField(max_length=150, verbose_name='policy id')),
                ('age', models.IntegerField(verbose_name='age')),
                ('social_grade', models.IntegerField(verbose_name='social grade')),
                ('payment', models.IntegerField(verbose_name='paymenent at purchase')),
                ('attribute_brand', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='attribute brand')),
                ('attribute_price', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='attribute price')),
                ('attribute_promotions', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='attribute promotions')),
                ('auto_renew', models.BooleanField(verbose_name='auto renew')),
                ('inertia', models.IntegerField(verbose_name='inertia for switch')),
                ('initial_breed', models.CharField(choices=[('Breed_C', 'Breed C'), ('Breed_NC', 'Breed NC')], max_length=8, verbose_name='initial breed')),
                ('c_lost', models.BooleanField(default=False, verbose_name='breed c lost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
